# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.2'

target 'pigfood' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pigfood
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'

end
