# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.2'

target 'pigfood' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/Yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  # Pods for pigfood
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'

  pod 'react-native-fetch-blob',
    :path => '../node_modules/react-native-fetch-blob'
    pod 'GoogleToolboxForMac/Logger' 
    pod 'GoogleToolboxForMac', '~> 2.1'

end
